services:
  bdd:
    image: "postgres:14-alpine"
    ports:
      - '${PORT_BDD}:${PG_PORT}'
    environment:
      POSTGRES_DB: '${PG_DB}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_USER: '${PG_USER}'
    volumes:
      - ./BACK/db/:/docker-entrypoint-initdb.d/
      - ./psql:/var/lib/postgresql/data
    container_name: bddLucileCam

  back:
    image: "node:18"
    working_dir: /home/server/Skillswap/BACK
    environment:
      PORT: '${PORT_EXPRESS}'
      SECRET: '${SECRET}'
      PUBLIC_URL: '${PUBLIC_URL}'
      TOKEN_SECRET: '${TOKEN_SECRET}'
      SECRET_POUR_EXPRESS_SESSION: '${SECRET_POUR_EXPRESS_SESSION}'
      PGUSER: '${PG_USER}'
      PGHOST: '${PG_HOST}'
      PGPASSWORD: '${PG_PASSWORD}'
      PGDATABASE: '${PG_DB}'
      PGPORT: '${PG_PORT}'
    ports:
      - '${PORT_BACK}:${PORT_EXPRESS}'
    volumes:
      - ./BACK:/home/server/Skillswap/BACK
      - node_modules_back:/home/server/Skillswap/BACK/node_modules
    command: >
      sh -c "ls -al /home/server/Skillswap/BACK && npm install && npm run dev"
    depends_on:
      - bdd

  front:
    image: "node:18"
    working_dir: /home/server/Skillswap/FRONT
    environment:
      #REACT_APP_API_URL: 'https://${API_URL}'
      REACT_APP_API_URL: 'https://${API_URL}:${PORT_EXPRESS}'
      #REACT_APP_API_URL: 'https://${API_URL}:${PORT_BACK}'
      #REACT_APP_API_URL: 'https://${PUBLIC_URL}:${PORT_BACK}'
      #REACT_APP_API_URL: 'http://${PUBLIC_URL}:${PORT_BACK}'
    ports:
      - '${PORT_FRONT}:${PORT_PARCEL}'
    volumes:
      - ./FRONT:/home/server/Skillswap/FRONT
      - node_modules_front:/home/server/Skillswap/FRONT/node_modules
    command: >
      sh -c "ls -al /home/server/Skillswap/FRONT && npm install && npm start"
    depends_on:
      - back

  adminer:
    image: adminer
    ports:
      - '${ADMINER_PORT}:8080'
    environment:
      ADMINER_DEFAULT_SERVER: '${ADMINER_DEFAULT_SERVER}'
    depends_on:
      - bdd

volumes:
  
  node_modules_back:
  node_modules_front:
