services:
  bdd:
    image: "postgres:14-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./BACK/db/:/docker-entrypoint-initdb.d/
      - ./psql:/var/lib/postgresql/data
    container_name: bddLucileCam

  back:
    image: "node:18"
    working_dir: /home/server/Skillswap/BACK
    environment:
      PORT: ${PORT}
      SECRET: ${SECRET
      PUBLIC_URL: ${PUBLIC_URL}
      TOKEN_SECRET: ${TOKEN_SECRET}
      SECRET_POUR_EXPRESS_SESSION: ${SECRET_POUR_EXPRESS_SESSION}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    ports:
      - "3000:3000"
    volumes:
      - ./BACK:/home/server/Skillswap/BACK
      # - ./BACK:/Skillswap/BACK
      - node_modules_back:/home/server/Skillswap/BACK/node_modules
    command: >
      sh -c "ls -al /home/server/Skillswap/BACK && npm install && npm run dev"
    depends_on:
      - bdd

  front:
    image: "node:18"
    working_dir: /home/server/Skillswap/FRONT
    environment:
      PORT: ${PORT}
      REACT_APP_URL: ${REACT_APP_URL}
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - "1234:1234"
    volumes:
      - ./FRONT:/home/server/Skillswap/FRONT
      # - ./FRONT:/Skillswap/FRONT
      - node_modules_front:/home/server/Skillswap/FRONT/node_modules
    command: >
      sh -c "ls -al /home/server/Skillswap/FRONT && npm install && npm start"
    depends_on:
      - back

  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
    depends_on:
      - bdd

volumes:
  
  node_modules_back:
  node_modules_front:
